In [1]:
import pandas as pd
import numpy as np

# NLP
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

# Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

# Clustering
from sklearn.cluster import KMeans

# Visualization
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv("Canada Immigration.csv")

df.head()

   Year    USA    UK
0  2004   6994  7524
1  2005   8392  7253
2  2006   9612  7136
3  2007   9460  8213
4  2008  10187  8976

In [5]:
print(df.columns)

Index(['Year', 'USA', 'UK'], dtype='str')

In [7]:
for col in df.columns:
    print(f"'{col}'")

'Year'
'USA'
'UK'

In [10]:
import pandas as pd

df = pd.read_csv('Canada Immigration.csv')
X = df.iloc[:, :-1].values  # all columns except last

In [11]:
kmeans = KMeans(n_clusters=3, random_state=42)

df['Cluster'] = kmeans.fit_predict(X)

df.head()

   Year    USA    UK  Cluster
0  2004   6994  7524        2
1  2005   8392  7253        2
2  2006   9612  7136        0
3  2007   9460  8213        0
4  2008  10187  8976        0

In [13]:
col = 'Immigration_Reason'  # update if needed

for i in range(3):
    print(f"\nCluster {i} Sample Reasons:")
    
    subset = df[df['Cluster'] == i]
    
    if col in df.columns:
        print(subset[col].head(5))
    else:
        print(f"Column '{col}' not found!")

Cluster 0 Sample Reasons:
Column 'Immigration_Reason' not found!

Cluster 1 Sample Reasons:
Column 'Immigration_Reason' not found!

Cluster 2 Sample Reasons:
Column 'Immigration_Reason' not found!

In [15]:
if hasattr(X, "toarray"):
    X_dense = X.toarray()
else:
    X_dense = X

In [16]:
df.to_csv("Clustered_Immigration_Data.csv", index=False)