In [1]:
# =========================
# 1. Import Libraries
# =========================
import pandas as pd
import numpy as np

# NLP
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

# Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

# Clustering
from sklearn.cluster import KMeans

# Visualization (optional)
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Download NLTK data (run once)
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [4]:
import pandas as pd

df = pd.read_csv('Upload CSV.csv')
df.head()

     Date  SN   Name  Gender  Class  Age  Weight  Height         Email ID
0  01-Apr   1   Abha       F    1.0  4.0      24     100   Abha@gmail.com
1  02-Apr   2  Akash       M    1.0  4.1      28     110  Akash@gmail.com
2  03-Apr   3   Aman    Male    1.0  4.3      30     102   Aman@gmail.com
3  04-Apr   4  Amber    Male    2.0  5.5      31     111  Amber@gmail.com
4  05-Apr   5   Ania  Female    2.0  5.6      29     121   Ania@gmail.com

In [6]:
print(df.columns)

Index(['Date', 'SN', 'Name', 'Gender', 'Class', 'Age', 'Weight', 'Height',
       'Email ID'],
      dtype='str')

In [8]:
print(df.columns)        # See actual names
print(df.head())         # Confirm data exists

Index(['Date', 'SN', 'Name', 'Gender', 'Class', 'Age', 'Weight', 'Height',
       'Email ID'],
      dtype='str')
     Date  SN   Name  Gender  Class  Age  Weight  Height         Email ID
0  01-Apr   1   Abha       F    1.0  4.0      24     100   Abha@gmail.com
1  02-Apr   2  Akash       M    1.0  4.1      28     110  Akash@gmail.com
2  03-Apr   3   Aman    Male    1.0  4.3      30     102   Aman@gmail.com
3  04-Apr   4  Amber    Male    2.0  5.5      31     111  Amber@gmail.com
4  05-Apr   5   Ania  Female    2.0  5.6      29     121   Ania@gmail.com

In [11]:
try:
    X = vectorizer.fit_transform(df['clean_text'])
    print(X.shape)
except Exception as e:
    print("Error:", e)

Error: 'clean_text'

In [13]:


df.head()

     Date  SN   Name  Gender  Class  Age  Weight  Height         Email ID
0  01-Apr   1   Abha       F    1.0  4.0      24     100   Abha@gmail.com
1  02-Apr   2  Akash       M    1.0  4.1      28     110  Akash@gmail.com
2  03-Apr   3   Aman    Male    1.0  4.3      30     102   Aman@gmail.com
3  04-Apr   4  Amber    Male    2.0  5.5      31     111  Amber@gmail.com
4  05-Apr   5   Ania  Female    2.0  5.6      29     121   Ania@gmail.com

In [17]:
print(df.isna().sum())

Date        0
SN          0
Name        0
Gender      0
Class       1
Age         0
Weight      0
Height      0
Email ID    0
dtype: int64

In [21]:
print("Columns:", df.columns)

# Clean column names
df.columns = df.columns.str.strip().str.lower()

print("Cleaned Columns:", df.columns)

Columns: Index(['Date', 'SN', 'Name', 'Gender', 'Class', 'Age', 'Weight', 'Height',
       'Email ID'],
      dtype='str')
Cleaned Columns: Index(['date', 'sn', 'name', 'gender', 'class', 'age', 'weight', 'height',
       'email id'],
      dtype='str')

In [22]:
df.columns = df.columns.str.strip()

In [23]:
print([col for col in df.columns])

['date', 'sn', 'name', 'gender', 'class', 'age', 'weight', 'height', 'email id']

In [27]:
print(df.head())
print(X.head())
print(df.columns)

     date  sn   name  gender  class  age  weight  height         email id
0  01-Apr   1   Abha       F    1.0  4.0      24     100   Abha@gmail.com
1  02-Apr   2  Akash       M    1.0  4.1      28     110  Akash@gmail.com
2  03-Apr   3   Aman    Male    1.0  4.3      30     102   Aman@gmail.com
3  04-Apr   4  Amber    Male    2.0  5.5      31     111  Amber@gmail.com
4  05-Apr   5   Ania  Female    2.0  5.6      29     121   Ania@gmail.com
   SN  Class  Age  Weight  Height
0   1    1.0  4.0      24     100
1   2    1.0  4.1      28     110
2   3    1.0  4.3      30     102
3   4    2.0  5.5      31     111
4   5    2.0  5.6      29     121
Index(['date', 'sn', 'name', 'gender', 'class', 'age', 'weight', 'height',
       'email id'],
      dtype='str')