In [1]:
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# ML Models
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load your dataset
df = pd.read_csv("eng.3.csv")

# Preview
df.head()

   Round             Date                 Team 1   FT                  Team 2
0      1  Sat Sep 12 2020  Accrington Stanley FC  2-0  Peterborough United FC
1      1  Sat Sep 12 2020     Crewe Alexandra FC  0-2    Charlton Athletic FC
2      1  Sat Sep 12 2020    Doncaster Rovers FC  1-1   Milton Keynes Dons FC
3      1  Sat Sep 12 2020      Fleetwood Town FC  2-1        Burton Albion FC
4      1  Sat Sep 12 2020          Gillingham FC  0-2           Hull City AFC

In [3]:
print(df.shape)
print(df.info())
print(df.describe())

# Check missing values
print(df.isnull().sum())

(552, 5)
<class 'pandas.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Round   552 non-null    int64
 1   Date    552 non-null    str
 2   Team 1  552 non-null    str
 3   FT      131 non-null    str
 4   Team 2  552 non-null    str
dtypes: int64(1), str(4)
memory usage: 47.8 KB
None
           Round
count  552.00000
mean    23.50000
std     13.28796
min      1.00000
25%     12.00000
50%     23.50000
75%     35.00000
max     46.00000
Round       0
Date        0
Team 1      0
FT        421
Team 2      0
dtype: int64

In [4]:
# Drop missing values (or replace with mean if needed)
df = df.dropna()

# Convert categorical columns (if any)
df = pd.get_dummies(df, drop_first=True)

In [6]:
df.head()

   Round  ...  Team 2_Wigan Athletic FC
0      1  ...                     False
1      1  ...                     False
2      1  ...                     False
3      1  ...                     False
4      1  ...                     False

[5 rows x 85 columns]

In [8]:
import numpy as np

X = np.array([...])  # your feature data
y = np.array([...])  # your labels

In [9]:
from sklearn.datasets import load_iris

data = load_iris()
X = data.data
y = data.target

In [13]:
print(df.columns)

Index(['Round', 'Date_Mon Nov 16 2020', 'Date_Sat Nov 14 2020',
       'Date_Sat Oct 10 2020', 'Date_Sat Oct 17 2020', 'Date_Sat Oct 24 2020',
       'Date_Sat Oct 3 2020', 'Date_Sat Oct 31 2020', 'Date_Sat Sep 12 2020',
       'Date_Sat Sep 19 2020', 'Date_Sat Sep 26 2020', 'Date_Sun Sep 13 2020',
       'Date_Sun Sep 20 2020', 'Date_Sun Sep 27 2020', 'Date_Tue Nov 3 2020',
       'Date_Tue Oct 20 2020', 'Date_Tue Oct 27 2020',
       'Team 1_Accrington Stanley FC', 'Team 1_Blackpool FC',
       'Team 1_Bristol Rovers FC', 'Team 1_Burton Albion FC',
       'Team 1_Charlton Athletic FC', 'Team 1_Crewe Alexandra FC',
       'Team 1_Doncaster Rovers FC', 'Team 1_Fleetwood Town FC',
       'Team 1_Gillingham FC', 'Team 1_Hull City AFC',
       'Team 1_Ipswich Town FC', 'Team 1_Lincoln City FC',
       'Team 1_Milton Keynes Dons FC', 'Team 1_Northampton Town FC',
       'Team 1_Oxford United FC', 'Team 1_Peterborough United FC',
       'Team 1_Plymouth Argyle FC', 'Team 1_Portsmouth FC',
       'Team 1_Rochdale AFC', 'Team 1_Shrewsbury Town FC',
       'Team 1_Sunderland AFC', 'Team 1_Swindon Town FC',
       'Team 1_Wigan Athletic FC', 'FT_0-1', 'FT_0-2', 'FT_0-3', 'FT_1-0',
       'FT_1-1', 'FT_1-2', 'FT_1-3', 'FT_1-4', 'FT_2-0', 'FT_2-1', 'FT_2-2',
       'FT_2-3', 'FT_2-4', 'FT_3-0', 'FT_3-1', 'FT_3-2', 'FT_3-3', 'FT_4-0',
       'FT_4-1', 'FT_4-2', 'FT_4-4', 'FT_5-1', 'Team 2_Accrington Stanley FC',
       'Team 2_Blackpool FC', 'Team 2_Bristol Rovers FC',
       'Team 2_Burton Albion FC', 'Team 2_Charlton Athletic FC',
       'Team 2_Crewe Alexandra FC', 'Team 2_Doncaster Rovers FC',
       'Team 2_Fleetwood Town FC', 'Team 2_Gillingham FC',
       'Team 2_Hull City AFC', 'Team 2_Ipswich Town FC',
       'Team 2_Lincoln City FC', 'Team 2_Milton Keynes Dons FC',
       'Team 2_Northampton Town FC', 'Team 2_Oxford United FC',
       'Team 2_Peterborough United FC', 'Team 2_Plymouth Argyle FC',
       'Team 2_Portsmouth FC', 'Team 2_Rochdale AFC',
       'Team 2_Shrewsbury Town FC', 'Team 2_Sunderland AFC',
       'Team 2_Swindon Town FC', 'Team 2_Wigan Athletic FC'],
      dtype='str')

In [16]:
print('y_test exists:', 'y_test' in globals())

y_test exists: False