In [1]:
# Core libraries
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load dataset
df = pd.read_csv("eng.5.csv")

# Preview
df.head()

   Round            Date             Team 1   FT                   Team 2
0      1  Sat Oct 3 2020      Altrincham FC  0-0              Weymouth FC
1      1  Sat Oct 3 2020  Dover Athletic FC  1-0          Notts County FC
2      1  Sat Oct 3 2020          Barnet FC  1-5             Eastleigh FC
3      1  Sat Oct 3 2020          Woking FC  2-1        Solihull Moors FC
4      1  Sat Oct 3 2020    FC Halifax Town  2-0  Dagenham & Redbridge FC

In [3]:
# Basic info
df.info()

# Check missing values
df.isnull().sum()

# Describe data
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Round   506 non-null    int64
 1   Date    506 non-null    str
 2   Team 1  506 non-null    str
 3   FT      80 non-null     str
 4   Team 2  506 non-null    str
dtypes: int64(1), str(4)
memory usage: 42.1 KB

            Round
count  506.000000
mean    23.500000
std     13.289056
min      1.000000
25%     12.000000
50%     23.500000
75%     35.000000
max     46.000000

In [5]:
from sklearn.preprocessing import LabelEncoder

for col in df.select_dtypes(include=['object', 'string']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

In [6]:
from sklearn.preprocessing import LabelEncoder

df = df.dropna()

for col in df.select_dtypes(include=['object', 'string']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

In [8]:
print(df.columns)

Index(['Round', 'Date', 'Team 1', 'FT', 'Team 2'], dtype='str')

In [13]:
print(df.head())

   Round  Date  Team 1  FT  Team 2
0      1     5       1   0      19
1      1     5       7   6      13
2      1     5       2  11       8
3      1     5      20  13      14
4      1     5       9  12       6

In [18]:
print(df.columns)

Index(['Round', 'Date', 'Team 1', 'FT', 'Team 2'], dtype='str')

In [20]:
print("Columns:", df.columns)

Columns: Index(['Round', 'Date', 'Team 1', 'FT', 'Team 2'], dtype='str')

In [24]:
print('y_test' in globals())

False

In [27]:
print(locals())

{'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, '__loader__': None, '__spec__': None, '__builtin__': <module 'builtins' (built-in)>, '__builtins__': <module 'builtins' (built-in)>, '_ih': ['', '# Core libraries\nimport pandas as pd\nimport numpy as np\n\n# Visualization\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\n# Preprocessing\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import LabelEncoder\n\n# Models\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import RandomForestClassifier\n\n# Evaluation\nfrom sklearn.metrics import accuracy_score, classification_report, confusion_matrix', '# Load dataset\ndf = pd.read_csv("eng.5.csv")\n\n# Preview\ndf.head()', '# Basic info\ndf.info()\n\n# Check missing values\ndf.isnull().sum()\n\n# Describe data\ndf.describe()', "# Drop missing values (or handle them differently if needed)\ndf = df.dropna()\n\n# Encode categorical columns\nle = LabelEncoder()\n\nfor col in df.select_dtypes(include='object').columns:\n    df[col] = le.fit_transform(df[col])", "from sklearn.preprocessing import LabelEncoder\n\nfor col in df.select_dtypes(include=['object', 'string']).columns:\n    le = LabelEncoder()\n    df[col] = le.fit_transform(df[col])", "from sklearn.preprocessing import LabelEncoder\n\ndf = df.dropna()\n\nfor col in df.select_dtypes(include=['object', 'string']).columns:\n    le = LabelEncoder()\n    df[col] = le.fit_transform(df[col])", '# Change \'target\' to your actual column name\nX = df.drop("target", axis=1)\ny = df["target"]', 'print(df.columns)', '# Initialize model\ndt_model = DecisionTreeClassifier(random_state=42)\n\n# Train\ndt_model.fit(X_train, y_train)\n\n# Predict\ny_pred_dt = dt_model.predict(X_test)\n\n# Evaluate\nprint("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred_dt))', 'from sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.metrics import accuracy_score, classification_report\n\n# Split data\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# Initialize model\ndt_model = DecisionTreeClassifier(random_state=42)\n\n# Train\ndt_model.fit(X_train, y_train)\n\n# Predict\ny_pred_dt = dt_model.predict(X_test)\n\n# Evaluate\nprint("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred_dt))', 'print(df.head())', '# Initialize model\nrf_model = RandomForestClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\n# Train\nrf_model.fit(X_train, y_train)\n\n# Predict\ny_pred_rf = rf_model.predict(X_test)\n\n# Evaluate\nprint("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred_rf))', 'print(df.head())', 'from sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import accuracy_score, classification_report\n\nrf_model = RandomForestClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\nrf_model.fit(X_train, y_train)\n\ny_pred_rf = rf_model.predict(X_test)\n\nprint("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred_rf))', 'from sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import accuracy_score, classification_report\n\nrf_model = RandomForestClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\nrf_model.fit(X_train, y_train)\n\ny_pred_rf = rf_model.predict(X_test)\n\nprint("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred_rf))', 'from sklearn.model_selection import train_test_split\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)', 'print(df.shape)   # does df exist?\nprint(X.shape)    # does X exist?\nprint(X_train.shape)  # does split exist?', 'print(df.columns)', '# 1. Import libraries\nimport pandas as pd\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import accuracy_score, classification_report\n\n# 2. Load dataset\ndf = pd.read_csv("eng.5.csv")  # <-- change to your file path\n\n# 3. Inspect columns (optional but useful)\nprint("Columns:", df.columns)\n\n# 4. Define target column (CHANGE THIS)\ntarget_column = \'target\'   # <-- replace with your actual target column\n\n# 5. Create features (X) and labels (y)\nX = df.drop(target_column, axis=1)\ny = df[target_column]\n\n# 6. Handle non-numeric data (basic encoding)\nX = pd.get_dummies(X, drop_first=True)\n\n# 7. Train-test split\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# 8. Initialize model\nrf_model = RandomForestClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\n# 9. Train model\nrf_model.fit(X_train, y_train)\n\n# 10. Make predictions\ny_pred_rf = rf_model.predict(X_test)\n\n# 11. Evaluate model\nprint("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred_rf))', 'print("Columns:", df.columns)', '# Decision Tree\nsns.heatmap(confusion_matrix(y_test, y_pred_dt), annot=True, fmt=\'d\')\nplt.title("Decision Tree Confusion Matrix")\nplt.show()\n\n# Random Forest\nsns.heatmap(confusion_matrix(y_test, y_pred_rf), annot=True, fmt=\'d\')\nplt.title("Random Forest Confusion Matrix")\nplt.show()', 'import seaborn as sns\nimport matplotlib.pyplot as plt\nfrom sklearn.metrics import confusion_matrix\n\n# Decision Tree\nsns.heatmap(confusion_matrix(y_test, y_pred_dt), annot=True, fmt=\'d\')\nplt.title("Decision Tree Confusion Matrix")\nplt.show()\n\n# Random Forest\nsns.heatmap(confusion_matrix(y_test, y_pred_rf), annot=True, fmt=\'d\')\nplt.title("Random Forest Confusion Matrix")\nplt.show()', 'from sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import RandomForestClassifier\n\n# Example: replace X and y with your actual dataset\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\n# Train models\ndt = DecisionTreeClassifier()\nrf = RandomForestClassifier()\n\ndt.fit(X_train, y_train)\nrf.fit(X_train, y_train)\n\n# Predictions\ny_pred_dt = dt.predict(X_test)\ny_pred_rf = rf.predict(X_test)', "print('y_test' in globals())", 'importances = rf_model.feature_importances_\nfeatures = X.columns\n\n# Plot\nplt.figure(figsize=(10,5))\nplt.barh(features, importances)\nplt.title("Feature Importance (Random Forest)")\nplt.show()', 'from sklearn.ensemble import RandomForestClassifier\nimport matplotlib.pyplot as plt\n\n# Create model\nrf_model = RandomForestClassifier(random_state=42)\n\n# Fit model\nrf_model.fit(X, y)\n\n# Get feature importances\nimportances = rf_model.feature_importances_\nfeatures = X.columns\n\n# Plot\nplt.figure(figsize=(10,5))\nplt.barh(features, importances)\nplt.title("Feature Importance (Random Forest)")\nplt.xlabel("Importance")\nplt.show()', 'print(locals())'], '_oh': {2:    Round            Date             Team 1   FT                   Team 2
0      1  Sat Oct 3 2020      Altrincham FC  0-0              Weymouth FC
1      1  Sat Oct 3 2020  Dover Athletic FC  1-0          Notts County FC
2      1  Sat Oct 3 2020          Barnet FC  1-5             Eastleigh FC
3      1  Sat Oct 3 2020          Woking FC  2-1        Solihull Moors FC
4      1  Sat Oct 3 2020    FC Halifax Town  2-0  Dagenham & Redbridge FC, 3:             Round
count  506.000000
mean    23.500000
std     13.289056
min      1.000000
25%     12.000000
50%     23.500000
75%     35.000000
max     46.000000}, '_dh': [PosixPath('/Users/adnanaltimeemy')], 'In': ['', '# Core libraries\nimport pandas as pd\nimport numpy as np\n\n# Visualization\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\n# Preprocessing\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import LabelEncoder\n\n# Models\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import RandomForestClassifier\n\n# Evaluation\nfrom sklearn.metrics import accuracy_score, classification_report, confusion_matrix', '# Load dataset\ndf = pd.read_csv("eng.5.csv")\n\n# Preview\ndf.head()', '# Basic info\ndf.info()\n\n# Check missing values\ndf.isnull().sum()\n\n# Describe data\ndf.describe()', "# Drop missing values (or handle them differently if needed)\ndf = df.dropna()\n\n# Encode categorical columns\nle = LabelEncoder()\n\nfor col in df.select_dtypes(include='object').columns:\n    df[col] = le.fit_transform(df[col])", "from sklearn.preprocessing import LabelEncoder\n\nfor col in df.select_dtypes(include=['object', 'string']).columns:\n    le = LabelEncoder()\n    df[col] = le.fit_transform(df[col])", "from sklearn.preprocessing import LabelEncoder\n\ndf = df.dropna()\n\nfor col in df.select_dtypes(include=['object', 'string']).columns:\n    le = LabelEncoder()\n    df[col] = le.fit_transform(df[col])", '# Change \'target\' to your actual column name\nX = df.drop("target", axis=1)\ny = df["target"]', 'print(df.columns)', '# Initialize model\ndt_model = DecisionTreeClassifier(random_state=42)\n\n# Train\ndt_model.fit(X_train, y_train)\n\n# Predict\ny_pred_dt = dt_model.predict(X_test)\n\n# Evaluate\nprint("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred_dt))', 'from sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.metrics import accuracy_score, classification_report\n\n# Split data\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# Initialize model\ndt_model = DecisionTreeClassifier(random_state=42)\n\n# Train\ndt_model.fit(X_train, y_train)\n\n# Predict\ny_pred_dt = dt_model.predict(X_test)\n\n# Evaluate\nprint("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred_dt))', 'print(df.head())', '# Initialize model\nrf_model = RandomForestClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\n# Train\nrf_model.fit(X_train, y_train)\n\n# Predict\ny_pred_rf = rf_model.predict(X_test)\n\n# Evaluate\nprint("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred_rf))', 'print(df.head())', 'from sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import accuracy_score, classification_report\n\nrf_model = RandomForestClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\nrf_model.fit(X_train, y_train)\n\ny_pred_rf = rf_model.predict(X_test)\n\nprint("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred_rf))', 'from sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import accuracy_score, classification_report\n\nrf_model = RandomForestClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\nrf_model.fit(X_train, y_train)\n\ny_pred_rf = rf_model.predict(X_test)\n\nprint("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred_rf))', 'from sklearn.model_selection import train_test_split\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)', 'print(df.shape)   # does df exist?\nprint(X.shape)    # does X exist?\nprint(X_train.shape)  # does split exist?', 'print(df.columns)', '# 1. Import libraries\nimport pandas as pd\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import accuracy_score, classification_report\n\n# 2. Load dataset\ndf = pd.read_csv("eng.5.csv")  # <-- change to your file path\n\n# 3. Inspect columns (optional but useful)\nprint("Columns:", df.columns)\n\n# 4. Define target column (CHANGE THIS)\ntarget_column = \'target\'   # <-- replace with your actual target column\n\n# 5. Create features (X) and labels (y)\nX = df.drop(target_column, axis=1)\ny = df[target_column]\n\n# 6. Handle non-numeric data (basic encoding)\nX = pd.get_dummies(X, drop_first=True)\n\n# 7. Train-test split\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\n# 8. Initialize model\nrf_model = RandomForestClassifier(\n    n_estimators=100,\n    random_state=42\n)\n\n# 9. Train model\nrf_model.fit(X_train, y_train)\n\n# 10. Make predictions\ny_pred_rf = rf_model.predict(X_test)\n\n# 11. Evaluate model\nprint("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))\nprint("\\nClassification Report:\\n", classification_report(y_test, y_pred_rf))', 'print("Columns:", df.columns)', '# Decision Tree\nsns.heatmap(confusion_matrix(y_test, y_pred_dt), annot=True, fmt=\'d\')\nplt.title("Decision Tree Confusion Matrix")\nplt.show()\n\n# Random Forest\nsns.heatmap(confusion_matrix(y_test, y_pred_rf), annot=True, fmt=\'d\')\nplt.title("Random Forest Confusion Matrix")\nplt.show()', 'import seaborn as sns\nimport matplotlib.pyplot as plt\nfrom sklearn.metrics import confusion_matrix\n\n# Decision Tree\nsns.heatmap(confusion_matrix(y_test, y_pred_dt), annot=True, fmt=\'d\')\nplt.title("Decision Tree Confusion Matrix")\nplt.show()\n\n# Random Forest\nsns.heatmap(confusion_matrix(y_test, y_pred_rf), annot=True, fmt=\'d\')\nplt.title("Random Forest Confusion Matrix")\nplt.show()', 'from sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import RandomForestClassifier\n\n# Example: replace X and y with your actual dataset\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\n# Train models\ndt = DecisionTreeClassifier()\nrf = RandomForestClassifier()\n\ndt.fit(X_train, y_train)\nrf.fit(X_train, y_train)\n\n# Predictions\ny_pred_dt = dt.predict(X_test)\ny_pred_rf = rf.predict(X_test)', "print('y_test' in globals())", 'importances = rf_model.feature_importances_\nfeatures = X.columns\n\n# Plot\nplt.figure(figsize=(10,5))\nplt.barh(features, importances)\nplt.title("Feature Importance (Random Forest)")\nplt.show()', 'from sklearn.ensemble import RandomForestClassifier\nimport matplotlib.pyplot as plt\n\n# Create model\nrf_model = RandomForestClassifier(random_state=42)\n\n# Fit model\nrf_model.fit(X, y)\n\n# Get feature importances\nimportances = rf_model.feature_importances_\nfeatures = X.columns\n\n# Plot\nplt.figure(figsize=(10,5))\nplt.barh(features, importances)\nplt.title("Feature Importance (Random Forest)")\nplt.xlabel("Importance")\nplt.show()', 'print(locals())'], 'Out': {2:    Round            Date             Team 1   FT                   Team 2
0      1  Sat Oct 3 2020      Altrincham FC  0-0              Weymouth FC
1      1  Sat Oct 3 2020  Dover Athletic FC  1-0          Notts County FC
2      1  Sat Oct 3 2020          Barnet FC  1-5             Eastleigh FC
3      1  Sat Oct 3 2020          Woking FC  2-1        Solihull Moors FC
4      1  Sat Oct 3 2020    FC Halifax Town  2-0  Dagenham & Redbridge FC, 3:             Round
count  506.000000
mean    23.500000
std     13.289056
min      1.000000
25%     12.000000
50%     23.500000
75%     35.000000
max     46.000000}, 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10359d400>>, 'exit': <IPython.core.autocall.ZMQExitAutocall object at 0x1039deb10>, 'quit': <IPython.core.autocall.ZMQExitAutocall object at 0x1039deb10>, 'open': <function open at 0x102550b80>, '_':             Round
count  506.000000
mean    23.500000
std     13.289056
min      1.000000
25%     12.000000
50%     23.500000
75%     35.000000
max     46.000000, '__':    Round            Date             Team 1   FT                   Team 2
0      1  Sat Oct 3 2020      Altrincham FC  0-0              Weymouth FC
1      1  Sat Oct 3 2020  Dover Athletic FC  1-0          Notts County FC
2      1  Sat Oct 3 2020          Barnet FC  1-5             Eastleigh FC
3      1  Sat Oct 3 2020          Woking FC  2-1        Solihull Moors FC
4      1  Sat Oct 3 2020    FC Halifax Town  2-0  Dagenham & Redbridge FC, '___': '', '__session__': '/Users/adnanaltimeemy/Untitled22.ipynb', '_i': 'from sklearn.ensemble import RandomForestClassifier\nimport matplotlib.pyplot as plt\n\n# Create model\nrf_model = RandomForestClassifier(random_state=42)\n\n# Fit model\nrf_model.fit(X, y)\n\n# Get feature importances\nimportances = rf_model.feature_importances_\nfeatures = X.columns\n\n# Plot\nplt.figure(figsize=(10,5))\nplt.barh(features, importances)\nplt.title("Feature Importance (Random Forest)")\nplt.xlabel("Importance")\nplt.show()', '_ii': 'importances = rf_model.feature_importances_\nfeatures = X.columns\n\n# Plot\nplt.figure(figsize=(10,5))\nplt.barh(features, importances)\nplt.title("Feature Importance (Random Forest)")\nplt.show()', '_iii': "print('y_test' in globals())", '_i1': '# Core libraries\nimport pandas as pd\nimport numpy as np\n\n# Visualization\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\n# Preprocessing\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import LabelEncoder\n\n# Models\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import RandomForestClassifier\n\n# Evaluation\nfrom sklearn.metrics import accuracy_score, classification_report, confusion_matrix', 'pd': <module 'pandas' from '/Users/adnanaltimeemy/miniconda3/envs/coding/lib/python3.12/site-packages/pandas/__init__.py'>, 'np': <module 'numpy' from '/Users/adnanaltimeemy/miniconda3/envs/coding/lib/python3.12/site-packages/numpy/__init__.py'>, 'plt': <module 'matplotlib.pyplot' from '/Users/adnanaltimeemy/miniconda3/envs/coding/lib/python3.12/site-packages/matplotlib/pyplot.py'>, 'sns': <module 'seaborn' from '/Users/adnanaltimeemy/miniconda3/envs/coding/lib/python3.12/site-packages/seaborn/__init__.py'>, 'train_test_split': <function train_test_split at 0x125f34f40>, 'LabelEncoder': <class 'sklearn.preprocessing._label.LabelEncoder'>, 'DecisionTreeClassifier': <class 'sklearn.tree._classes.DecisionTreeClassifier'>, 'RandomForestClassifier': <class 'sklearn.ensemble._forest.RandomForestClassifier'>, 'accuracy_score': <function accuracy_score at 0x11671fce0>, 'classification_report': <function classification_report at 0x1167411c0>, 'confusion_matrix': <function confusion_matrix at 0x11671fe20>, '_i2': '# Load dataset\ndf = pd.read_csv("eng.5.csv")\n\n# Preview\ndf.head()', 'df':      Round             Date                Team 1   FT                   Team 2
0        1   Sat Oct 3 2020         Altrincham FC  0-0              Weymouth FC
1        1   Sat Oct 3 2020     Dover Athletic FC  1-0          Notts County FC
2        1   Sat Oct 3 2020             Barnet FC  1-5             Eastleigh FC
3        1   Sat Oct 3 2020             Woking FC  2-1        Solihull Moors FC
4        1   Sat Oct 3 2020       FC Halifax Town  2-0  Dagenham & Redbridge FC
..     ...              ...                   ...  ...                      ...
501     46  Sat May 29 2021       FC Halifax Town  NaN          Chesterfield FC
502     46  Sat May 29 2021  Hartlepool United FC  NaN        Dover Athletic FC
503     46  Sat May 29 2021        King's Lynn FC  NaN        Aldershot Town FC
504     46  Sat May 29 2021     Solihull Moors FC  NaN             Eastleigh FC
505     46  Sat May 29 2021        Yeovil Town FC  NaN      Stockport County FC


In [28]:
df.head()

   Round            Date             Team 1   FT                   Team 2
0      1  Sat Oct 3 2020      Altrincham FC  0-0              Weymouth FC
1      1  Sat Oct 3 2020  Dover Athletic FC  1-0          Notts County FC
2      1  Sat Oct 3 2020          Barnet FC  1-5             Eastleigh FC
3      1  Sat Oct 3 2020          Woking FC  2-1        Solihull Moors FC
4      1  Sat Oct 3 2020    FC Halifax Town  2-0  Dagenham & Redbridge FC