In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
# Load dataset
df = pd.read_csv('Google_Stock_Price_Train.csv')

# Preview
df.head()

       Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

In [5]:
df.columns = df.columns.str.strip()

if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.sort_values('Date')
    df = df.drop(columns=['Date'])
else:
    print("No 'Date' column found. Using index instead.")
    df = df.sort_index()

df = df.ffill()

No 'Date' column found. Using index instead.

In [6]:
X = df.drop(columns=['Close'])  # Features
y = df['Close']                # Target

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

In [10]:
X_train.head()

     Open    High     Low      Volume
0  325.25  332.83  324.97   7,380,500
1  331.27  333.87  329.08   5,749,400
2  329.83  330.75  326.89   6,590,300
3  328.34  328.77  323.68   5,405,900
4  322.04  322.29  309.46  11,688,800

In [16]:
print(X_train.dtypes)

Open      float64
High      float64
Low       float64
Volume        str
dtype: object

In [19]:
print('y_pred_dt' in globals())

False