In [1]:
# If needed (run once)
# !pip install pandas numpy scikit-learn nltk matplotlib seaborn

import pandas as pd
import numpy as np

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load your dataset
df = pd.read_csv("points_ALL_categories_2019.csv")

# Preview
df.head()

,Unnamed: 0,Point_ID,Region,Province Code,Crop Type,Month Start Date,Month End Date,ACI Crop ID,Longitude,Latitude,File Name,Available
0,0,1,Alberta,AB,pasture,2019-06-01,2019-06-30,122,-116.273783,50.774922,POINT_1_201906_AB_PASTURE,False
1,1,1,Alberta,AB,pasture,2019-07-01,2019-07-31,122,-116.273783,50.774922,POINT_1_201907_AB_PASTURE,True
2,2,1,Alberta,AB,pasture,2019-08-01,2019-08-31,122,-116.273783,50.774922,POINT_1_201908_AB_PASTURE,True
3,3,1,Alberta,AB,pasture,2019-09-01,2019-09-30,122,-116.273783,50.774922,POINT_1_201909_AB_PASTURE,False
4,4,1,Alberta,AB,pasture,2019-10-01,2019-10-31,122,-116.273783,50.774922,POINT_1_201910_AB_PASTURE,False

In [3]:
df.info()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 24920 entries, 0 to 24919
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        24920 non-null  int64
 1   Point_ID          24920 non-null  int64
 2   Region            24920 non-null  str
 3   Province Code     24920 non-null  str
 4   Crop Type         24920 non-null  str
 5   Month Start Date  24920 non-null  str
 6   Month End Date    24920 non-null  str
 7   ACI Crop ID       24920 non-null  int64
 8   Longitude         24920 non-null  float64
 9   Latitude          24920 non-null  float64
 10  File Name         24920 non-null  str
 11  Available         24920 non-null  bool
dtypes: bool(1), float64(2), int64(3), str(6)
memory usage: 3.7 MB

Index(['Unnamed: 0', 'Point_ID', 'Region', 'Province Code', 'Crop Type',
       'Month Start Date', 'Month End Date', 'ACI Crop ID', 'Longitude',
       'Latitude', 'File Name', 'Available'],
      dtype='str')

In [6]:
print(df.columns)

Index(['Unnamed: 0', 'Point_ID', 'Region', 'Province Code', 'Crop Type',
       'Month Start Date', 'Month End Date', 'ACI Crop ID', 'Longitude',
       'Latitude', 'File Name', 'Available'],
      dtype='str')

In [8]:
df.head()

,Unnamed: 0,Point_ID,Region,Province Code,Crop Type,Month Start Date,Month End Date,ACI Crop ID,Longitude,Latitude,File Name,Available
0,0,1,Alberta,AB,pasture,2019-06-01,2019-06-30,122,-116.273783,50.774922,POINT_1_201906_AB_PASTURE,False
1,1,1,Alberta,AB,pasture,2019-07-01,2019-07-31,122,-116.273783,50.774922,POINT_1_201907_AB_PASTURE,True
2,2,1,Alberta,AB,pasture,2019-08-01,2019-08-31,122,-116.273783,50.774922,POINT_1_201908_AB_PASTURE,True
3,3,1,Alberta,AB,pasture,2019-09-01,2019-09-30,122,-116.273783,50.774922,POINT_1_201909_AB_PASTURE,False
4,4,1,Alberta,AB,pasture,2019-10-01,2019-10-31,122,-116.273783,50.774922,POINT_1_201910_AB_PASTURE,False

In [10]:
import numpy as np

X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [12]:
print(X.shape)
print(df.shape)

(3, 2)
(24920, 12)

In [13]:
df = df.dropna()

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import KMeans

documents = ["I love data science", "AI is amazing", "data science is fun"]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

k = 2
kmeans = KMeans(n_clusters=k, random_state=42)
kmeans.fit(X)

terms = vectorizer.get_feature_names_out()

for i in range(k):
    print(f"\nCluster {i}:")
    center = kmeans.cluster_centers_[i]
    top_words = [terms[ind] for ind in center.argsort()[-10:]]
    print(top_words)

Cluster 0:
['data', 'fun', 'love', 'science', 'ai', 'amazing', 'is']

Cluster 1:
['ai', 'amazing', 'fun', 'is', 'love', 'data', 'science']

In [16]:
df.to_csv("clustered_points_2019.csv", index=False)