In [1]:
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Model tools
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
# Load dataset (make sure file is in same directory or give full path)
df = pd.read_csv("Sonar Mine Rock Data.csv", header=None)

# Preview
df.head()

       0       1       2       3       4   ...      56      57      58      59 60
0      X1      X2      X3      X4      X5  ...     X57     X58     X59     X60  y
1    0.02  0.0371  0.0428  0.0207  0.0954  ...   0.018  0.0084   0.009  0.0032  R
2  0.0453  0.0523  0.0843  0.0689  0.1183  ...   0.014  0.0049  0.0052  0.0044  R
3  0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078  R
4    0.01  0.0171  0.0623  0.0205  0.0205  ...   0.005  0.0044   0.004  0.0117  R

[5 rows x 61 columns]

In [3]:
# 60 features + 1 label
columns = [f"feature_{i}" for i in range(60)] + ["label"]
df.columns = columns

df.head()

  feature_0 feature_1 feature_2  ... feature_58 feature_59 label
0        X1        X2        X3  ...        X59        X60     y
1      0.02    0.0371    0.0428  ...      0.009     0.0032     R
2    0.0453    0.0523    0.0843  ...     0.0052     0.0044     R
3    0.0262    0.0582    0.1099  ...     0.0095     0.0078     R
4      0.01    0.0171    0.0623  ...      0.004     0.0117     R

[5 rows x 61 columns]

In [4]:
print(df.shape)
print(df['label'].value_counts())

df.describe()

(209, 61)
label
M    111
R     97
y      1
Name: count, dtype: int64

       feature_0 feature_1 feature_2  ... feature_58 feature_59 label
count        209       209       209  ...        209        209   209
unique       178       183       191  ...        120        110     3
top       0.0201    0.0523    0.0623  ...      0.007     0.0053     M
freq           5         2         2  ...          6          7   111

[4 rows x 61 columns]

In [5]:
df['label'] = df['label'].map({'R': 0, 'M': 1})

In [6]:
X = df.drop('label', axis=1)
y = df['label']

In [8]:
print(y[y.isna()])

0   NaN
Name: label, dtype: float64

In [11]:
print(df.head())
print(df.columns)

  feature_0 feature_1 feature_2  ... feature_58 feature_59 label
0        X1        X2        X3  ...        X59        X60   NaN
1      0.02    0.0371    0.0428  ...      0.009     0.0032   0.0
2    0.0453    0.0523    0.0843  ...     0.0052     0.0044   0.0
3    0.0262    0.0582    0.1099  ...     0.0095     0.0078   0.0
4      0.01    0.0171    0.0623  ...      0.004     0.0117   0.0

[5 rows x 61 columns]
Index(['feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4',
       'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9',
       'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14',
       'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19',
       'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24',
       'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29',
       'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34',
       'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39',
       'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44',
       'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49',
       'feature_50', 'feature_51', 'feature_52', 'feature_53', 'feature_54',
       'feature_55', 'feature_56', 'feature_57', 'feature_58', 'feature_59',
       'label'],
      dtype='str')

In [14]:
X.head()

  feature_0 feature_1 feature_2  ... feature_57 feature_58 feature_59
0        X1        X2        X3  ...        X58        X59        X60
1      0.02    0.0371    0.0428  ...     0.0084      0.009     0.0032
2    0.0453    0.0523    0.0843  ...     0.0049     0.0052     0.0044
3    0.0262    0.0582    0.1099  ...     0.0164     0.0095     0.0078
4      0.01    0.0171    0.0623  ...     0.0044      0.004     0.0117

[5 rows x 60 columns]

In [15]:
print(X.dtypes)

feature_0     str
feature_1     str
feature_2     str
feature_3     str
feature_4     str
feature_5     str
feature_6     str
feature_7     str
feature_8     str
feature_9     str
feature_10    str
feature_11    str
feature_12    str
feature_13    str
feature_14    str
feature_15    str
feature_16    str
feature_17    str
feature_18    str
feature_19    str
feature_20    str
feature_21    str
feature_22    str
feature_23    str
feature_24    str
feature_25    str
feature_26    str
feature_27    str
feature_28    str
feature_29    str
feature_30    str
feature_31    str
feature_32    str
feature_33    str
feature_34    str
feature_35    str
feature_36    str
feature_37    str
feature_38    str
feature_39    str
feature_40    str
feature_41    str
feature_42    str
feature_43    str
feature_44    str
feature_45    str
feature_46    str
feature_47    str
feature_48    str
feature_49    str
feature_50    str
feature_51    str
feature_52    str
feature_53    str
feature_54    str
feature_55    str
feature_56    str
feature_57    str
feature_58    str
feature_59    str
dtype: object

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in X_train.columns:
    if X_train[col].dtype == 'object':
        X_train[col] = le.fit_transform(X_train[col])
        X_test[col] = le.transform(X_test[col])

In [22]:
X_train.isna().sum()
y_train.isna().sum()

np.int64(1)

In [27]:
print(dt_model)

DecisionTreeClassifier(max_depth=5, random_state=42)